### ISSUE TITLE
Could you please upload your CocConfig for C#?

### ISSUE THREAD

**Issue by lubyrex** [taotao7/dotfile#1]
Hi @taotao7,

I noticed you left a comment on Gitter about using Omnisharp-rosyln with Coc-vim. Did it end up working out for you? If so could you please tell me how you configured CocConfig to get it to work? Thanks a lot!

**Comment by taotao7** [comment]
yes ,i download that file. u can wait for the plug automatically  ,then you get the site download the plug file, put it here c:/user/xxx/AppData/Local/coc

**Comment by lubyrex** [comment]
啊我没太看懂，所以想问下你的vim现在可以集成Omnisharp-rosyln 和 Coc-vim吗？

**Comment by taotao7** [comment]
可以啊，你先用自动下载看看c#的那个插件是下载在哪里，然后自己手动去下载放在自动下载的位置，我是很之前去弄的所以现在我也不记得路径了，你只能自己尝试，只需要自己手动下载就行了，还有一个办法最简单无脑，挂梯子全局的，然后market里面下载c#的lsp就行了

发自我的iPhone

**Comment by lubyrex** [comment]
啊好的，我试试，多谢了
